In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as scipy_stats
import gpboost as gpb
import patsy
import re

In [15]:
results_path = 'results_0'
formats = ['parquet', 'delta', 'hudi', 'iceberg']
data_sets = ['tpcds_1', 'tpcds_10', 'tpcds_100']
optimizations = ['none', 'zorder', 'bloom', 'partitioning']
block_sizes = ['64MiB', '128MiB', '256MiB']
data_frames = []

In [16]:
for format in formats:
    for data_set in data_sets:
        for optimization in optimizations:
            for block_size in block_sizes:
                if format == 'parquet' and (optimization != 'none' or block_size != '128MiB'):
                    continue
                
                file_path = f'{results_path}/{format}/{data_set}/{optimization}/{block_size}/results.csv'
                df = pd.read_csv(file_path)
                df['format'] = format
                df['data_set'] = data_set
                df['optimization'] = optimization
                df['block_size'] = block_size
                data_frames.append(df)

In [17]:
master_df = pd.concat(data_frames, ignore_index=True)
target_metric = 'elapsedTime'
master_df[target_metric] = master_df[target_metric].round(2)
summary_stats_by_query = master_df.groupby(['format', 'data_set', 'optimization', 'block_size', 'query'])[target_metric].agg(
    mean='mean',
    median='median',
    std='std',
    min='min',
    max='max',
    cv=lambda x: np.std(x, ddof=1) / np.mean(x) * 100 # coef of variation
).reset_index()
display(summary_stats_by_query)

,format,data_set,optimization,block_size,query,mean,median,std,min,max,cv
0,delta,tpcds_1,bloom,128MiB,q1,694.2,438.5,805.629885,430,2987,116.051554
1,delta,tpcds_1,bloom,128MiB,q10,1200.3,1190.5,39.477279,1138,1272,3.288951
2,delta,tpcds_1,bloom,128MiB,q10a,1148.6,1113.0,63.328421,1095,1260,5.513531
3,delta,tpcds_1,bloom,128MiB,q11,917.8,905.5,76.179321,869,1128,8.300209
4,delta,tpcds_1,bloom,128MiB,q12,96.3,92.0,10.698390,88,124,11.109440
...,...,...,...,...,...,...,...,...,...,...,...
13093,parquet,tpcds_100,none,128MiB,q95,22784.9,22728.0,501.340525,22001,23567,2.200319
13094,parquet,tpcds_100,none,128MiB,q96,1099.5,1084.5,59.920781,1013,1199,5.449821
13095,parquet,tpcds_100,none,128MiB,q97,11490.2,11499.0,75.596590,11346,11599,0.657922
13096,parquet,tpcds_100,none,128MiB,q98,2101.2,1993.5,345.296266,1847,3047,16.433289
13097,parquet,tpcds_100,none,128MiB,q99,1848.1,1830.0,110.013585,1713,2101,5.952794

In [18]:
print("--- Shapiro-Wilk Test for Normality ---")
groups_shapiro = master_df.groupby(['format', 'data_set', 'optimization', 'block_size', 'query'])[target_metric].apply(list)

df_shapiro_list = []

for name, group_data in groups_shapiro.items():
    stat, p_val = scipy_stats.shapiro(group_data)

    df_shapiro_list.append({
        'Group': name,
        'W_Statistic': stat,
        'p_value': p_val.round(4),
        'Distribution': 'Normal' if p_val > 0.05 else 'Not Normal'
    })

df_shapiro = pd.DataFrame(df_shapiro_list)
display(df_shapiro)

df_shapiro_normal = df_shapiro[df_shapiro['Distribution'] == 'Normal']
display(df_shapiro_normal)

df_shapiro_not_normal = df_shapiro[df_shapiro['Distribution'] == 'Not Normal']
display(df_shapiro_not_normal)

--- Shapiro-Wilk Test for Normality ---

/home/heavylight/ResultsAnalysis/.venv/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:592: UserWarning: scipy.stats.shapiro: Input data has range zero. The results may not be accurate.
  res = hypotest_fun_out(*samples, **kwds)

,Group,W_Statistic,p_value,Distribution
0,"(delta, tpcds_1, bloom, 128MiB, q1)",0.372588,0.0000,Not Normal
1,"(delta, tpcds_1, bloom, 128MiB, q10)",0.934044,0.4888,Normal
2,"(delta, tpcds_1, bloom, 128MiB, q10a)",0.804009,0.0162,Not Normal
3,"(delta, tpcds_1, bloom, 128MiB, q11)",0.590802,0.0000,Not Normal
4,"(delta, tpcds_1, bloom, 128MiB, q12)",0.721175,0.0016,Not Normal
...,...,...,...,...
13093,"(parquet, tpcds_100, none, 128MiB, q95)",0.961838,0.8066,Normal
13094,"(parquet, tpcds_100, none, 128MiB, q96)",0.952258,0.6953,Normal
13095,"(parquet, tpcds_100, none, 128MiB, q97)",0.938044,0.5315,Normal
13096,"(parquet, tpcds_100, none, 128MiB, q98)",0.626746,0.0001,Not Normal
13097,"(parquet, tpcds_100, none, 128MiB, q99)",0.884626,0.1474,Normal

,Group,W_Statistic,p_value,Distribution
1,"(delta, tpcds_1, bloom, 128MiB, q10)",0.934044,0.4888,Normal
6,"(delta, tpcds_1, bloom, 128MiB, q14)",0.938551,0.5370,Normal
8,"(delta, tpcds_1, bloom, 128MiB, q14b)",0.862004,0.0806,Normal
9,"(delta, tpcds_1, bloom, 128MiB, q15)",0.921950,0.3735,Normal
11,"(delta, tpcds_1, bloom, 128MiB, q17)",0.943248,0.5897,Normal
...,...,...,...,...
13091,"(parquet, tpcds_100, none, 128MiB, q93)",0.907208,0.2624,Normal
13093,"(parquet, tpcds_100, none, 128MiB, q95)",0.961838,0.8066,Normal
13094,"(parquet, tpcds_100, none, 128MiB, q96)",0.952258,0.6953,Normal
13095,"(parquet, tpcds_100, none, 128MiB, q97)",0.938044,0.5315,Normal
13097,"(parquet, tpcds_100, none, 128MiB, q99)",0.884626,0.1474,Normal

,Group,W_Statistic,p_value,Distribution
0,"(delta, tpcds_1, bloom, 128MiB, q1)",0.372588,0.0000,Not Normal
2,"(delta, tpcds_1, bloom, 128MiB, q10a)",0.804009,0.0162,Not Normal
3,"(delta, tpcds_1, bloom, 128MiB, q11)",0.590802,0.0000,Not Normal
4,"(delta, tpcds_1, bloom, 128MiB, q12)",0.721175,0.0016,Not Normal
5,"(delta, tpcds_1, bloom, 128MiB, q13)",0.447797,0.0000,Not Normal
...,...,...,...,...
13060,"(parquet, tpcds_100, none, 128MiB, q69)",0.797005,0.0133,Not Normal
13063,"(parquet, tpcds_100, none, 128MiB, q70a)",0.545676,0.0000,Not Normal
13074,"(parquet, tpcds_100, none, 128MiB, q8)",0.742627,0.0029,Not Normal
13092,"(parquet, tpcds_100, none, 128MiB, q94)",0.555992,0.0000,Not Normal
13096,"(parquet, tpcds_100, none, 128MiB, q98)",0.626746,0.0001,Not Normal

In [19]:
master_df = pd.concat(data_frames, ignore_index=True)
summary_stats_aggregated_runs = master_df.groupby(['format', 'data_set', 'optimization', 'block_size', 'run_id'])[['elapsedTime']].sum().reset_index()
display(summary_stats_aggregated_runs)

       format   data_set optimization block_size  run_id  elapsedTime
0       delta    tpcds_1        bloom     128MiB       0       102304
1       delta    tpcds_1        bloom     128MiB       1        89034
2       delta    tpcds_1        bloom     128MiB       2        90110
3       delta    tpcds_1        bloom     128MiB       3        88166
4       delta    tpcds_1        bloom     128MiB       4        87548
...       ...        ...          ...        ...     ...          ...
1105  parquet  tpcds_100         none     128MiB       5      1698289
1106  parquet  tpcds_100         none     128MiB       6      1755832
1107  parquet  tpcds_100         none     128MiB       7      1827483
1108  parquet  tpcds_100         none     128MiB       8      1722880
1109  parquet  tpcds_100         none     128MiB       9      1655985

[1110 rows x 6 columns]

In [20]:
target_metrics = ['elapsedTime', 'executorCpuTime', 'executorRunTime', 'resultSize', 'peakExecutionMemory', 'shuffleTotalBytesRead', 'shuffleBytesWritten']
EPSILON = 1e-6

In [21]:
def print_df_latex(df, caption):
    latex_output = (
        df.style
        .hide(axis='index')
        .to_latex(
            caption=caption, 
            position='h!', 
            position_float='centering',
            hrules=True
        )
    )
    lines = latex_output.split('\n')
    caption_line = next((l for l in lines if l.strip().startswith('\\caption{')), None)
    
    if caption_line:
        lines.remove(caption_line)
        # Find the index of \end{table} and insert the caption before it
        end_table_idx = next(i for i, l in enumerate(lines) if l.strip() == '\\end{table}')
        lines.insert(end_table_idx, caption_line)
        latex_output = '\n'.join(lines)

    print(latex_output)

def clean_patsy_name(name):
    if name == 'Intercept':
        return name
    cleaned = re.sub(r'C\([^,)]+,\s*Treatment\([^)]+\)\)', '', name)
    cleaned = re.sub(r'\[T\.([^\]]+)\]', r' \1', cleaned)
    return cleaned.title().strip()

In [22]:
for target_metric in target_metrics:
        
    for data_set in data_sets:

        df_rq1 = master_df[
            (master_df['optimization'] == 'none') &
            (master_df['block_size'] == '128MiB') &
            (master_df['data_set'] == data_set) 
        ].copy()

        df_rq1['format'] = pd.Categorical(df_rq1['format'], categories=formats)

        y = df_rq1[target_metric].values + EPSILON
        group_data = df_rq1['query'].to_numpy()

        X_df = patsy.dmatrix('format', data=df_rq1, return_type='dataframe')
        X = X_df.values
        feature_names = X_df.columns.tolist()

        gp_model = gpb.GPModel(group_data=group_data, likelihood='gamma')
        gp_model.fit(y=y, X=X)
        fixed_effects, std_errs = gp_model.get_coef(format_pandas=False, std_err=True)

        summary_data = []
        for name, coef, std_err in zip(feature_names, fixed_effects, std_errs):
            z_stat = coef / std_err
            p_value = 2 * scipy_stats.norm.sf(np.abs(z_stat))
            pct_change = (np.exp(coef) - 1) * 100 if name != 'Intercept' else 0
            
            summary_data.append({
                'Factor': 'Format Parquet' if name == 'Intercept' else clean_patsy_name(name),
                'Coefficient $\\beta$': f'{coef:.4f}',
                'Std. Error': std_err  if name != 'Intercept' else '',
                'Percentage Change': f'{pct_change:+.1f}\\%',
                '$p$-Value': f'{p_value:.4f}' if name != 'Intercept' else '',
                '$H_0$ Rejected': str(p_value <= 0.05) if name != 'Intercept' else ''
            })

        summary_df = pd.DataFrame(summary_data)
        caption_text = f"TPC-DS {data_set.split('_')[1]}GB, {re.sub(r'(?<!^)(?=[A-Z])', ' ', target_metric).title()}"
        print_df_latex(summary_df, caption_text)

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 5.1505 &  & +0.0\% &  &  \\
Format Delta & 1.3351 & 0.019385 & +280.0\% & 0.0000 & True \\
Format Hudi & 0.1607 & 0.017432 & +17.4\% & 0.0000 & True \\
Format Iceberg & 0.0257 & nan & +2.6\% & nan & False \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 7.2501 &  & +0.0\% &  &  \\
Format Delta & 0.2512 & 0.006643 & +28.6\% & 0.0000 & True \\
Format Hudi & 0.0786 & 0.006636 & +8.2\% & 0.0000 & True \\
Format Iceberg & 0.0696 & 0.006660 & +7.2\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 8.5259 &  & +0.0\% &  &  \\
Format Delta & 0.0872 & 0.015046 & +9.1\% & 0.0000 & True \\
Format Hudi & 0.1634 & 0.015046 & +17.7\% & 0.0000 & True \\
Format Iceberg & 0.5060 & 0.015696 & +65.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 5.6166 &  & +0.0\% &  &  \\
Format Delta & 2.1946 & 0.037952 & +797.6\% & 0.0000 & True \\
Format Hudi & 0.3330 & 0.032212 & +39.5\% & 0.0000 & True \\
Format Iceberg & 0.0911 & 0.032587 & +9.5\% & 0.0052 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 9.1376 &  & +0.0\% &  &  \\
Format Delta & 0.1431 & 0.008218 & +15.4\% & 0.0000 & True \\
Format Hudi & 0.1180 & 0.008210 & +12.5\% & 0.0000 & True \\
Format Iceberg & 0.1159 & 0.008265 & +12.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 10.9260 &  & +0.0\% &  &  \\
Format Delta & 0.0258 & 0.011985 & +2.6\% & 0.0313 & True \\
Format Hudi & 0.2062 & 0.011644 & +22.9\% & 0.0000 & True \\
Format Iceberg & 0.3916 & 0.011937 & +47.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 5.8726 &  & +0.0\% &  &  \\
Format Delta & 2.4440 & 0.041921 & +1051.9\% & 0.0000 & True \\
Format Hudi & 0.2680 & 0.034239 & +30.7\% & 0.0000 & True \\
Format Iceberg & -0.0988 & 0.034964 & -9.4\% & 0.0047 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 9.5211 &  & +0.0\% &  &  \\
Format Delta & 0.1999 & 0.009731 & +22.1\% & 0.0000 & True \\
Format Hudi & 0.0978 & 0.009677 & +10.3\% & 0.0000 & True \\
Format Iceberg & 0.0885 & 0.009744 & +9.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 11.1347 &  & +0.0\% &  &  \\
Format Delta & 0.0580 & 0.016238 & +6.0\% & 0.0004 & True \\
Format Hudi & 0.1807 & 0.016133 & +19.8\% & 0.0000 & True \\
Format Iceberg & 0.5471 & 0.016880 & +72.8\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 12.9661 &  & +0.0\% &  &  \\
Format Delta & 1.1902 & 0.040932 & +228.8\% & 0.0000 & True \\
Format Hudi & 0.0915 & 0.035184 & +9.6\% & 0.0093 & True \\
Format Iceberg & -0.2538 & 0.035846 & -22.4\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 14.1281 &  & +0.0\% &  &  \\
Format Delta & 0.2422 & 0.026968 & +27.4\% & 0.0000 & True \\
Format Hudi & 0.3668 & 0.029003 & +44.3\% & 0.0000 & True \\
Format Iceberg & -0.1494 & 0.027136 & -13.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 14.5548 &  & +0.0\% &  &  \\
Format Delta & 0.0446 & nan & +4.6\% & nan & False \\
Format Hudi & 0.0441 & 0.020152 & +4.5\% & 0.0287 & True \\
Format Iceberg & 0.0853 & 0.020841 & +8.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 17.5623 &  & +0.0\% &  &  \\
Format Delta & 0.2328 & 0.065563 & +26.2\% & 0.0004 & True \\
Format Hudi & 0.0500 & 0.061210 & +5.1\% & 0.4138 & False \\
Format Iceberg & -0.1525 & 0.062452 & -14.1\% & 0.0146 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 21.4460 &  & +0.0\% &  &  \\
Format Delta & 0.0437 & 0.025473 & +4.5\% & 0.0860 & False \\
Format Hudi & 0.0284 & nan & +2.9\% & nan & False \\
Format Iceberg & -0.1436 & 0.022684 & -13.4\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 22.8040 &  & +0.0\% &  &  \\
Format Delta & 0.0503 & 0.028959 & +5.2\% & 0.0824 & False \\
Format Hudi & 0.0732 & nan & +7.6\% & nan & False \\
Format Iceberg & 0.1958 & 0.029293 & +21.6\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 14.2741 &  & +0.0\% &  &  \\
Format Delta & 0.1903 & 0.059629 & +21.0\% & 0.0014 & True \\
Format Hudi & 0.0694 & 0.058096 & +7.2\% & 0.2322 & False \\
Format Iceberg & 0.2646 & 0.060667 & +30.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 16.2212 &  & +0.0\% &  &  \\
Format Delta & -0.0033 & 0.020736 & -0.3\% & 0.8734 & False \\
Format Hudi & 0.0714 & 0.020613 & +7.4\% & 0.0005 & True \\
Format Iceberg & 0.6909 & 0.041938 & +99.6\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 18.1529 &  & +0.0\% &  &  \\
Format Delta & -0.0016 & nan & -0.2\% & nan & False \\
Format Hudi & 0.1606 & 0.038788 & +17.4\% & 0.0000 & True \\
Format Iceberg & 1.4546 & 0.049741 & +328.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 13.9611 &  & +0.0\% &  &  \\
Format Delta & 0.2194 & 0.054464 & +24.5\% & 0.0001 & True \\
Format Hudi & 0.0783 & nan & +8.1\% & nan & False \\
Format Iceberg & 0.2493 & 0.055524 & +28.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 1GB, Shuffle Bytes Written}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 16.1367 &  & +0.0\% &  &  \\
Format Delta & -0.0002 & 0.003936 & -0.0\% & 0.9614 & False \\
Format Hudi & 0.0767 & 0.033091 & +8.0\% & 0.0204 & True \\
Format Iceberg & 0.6676 & 0.042742 & +94.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 10GB, Shuffle Bytes Written}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
Format Parquet & 18.0160 &  & +0.0\% &  &  \\
Format Delta & 0.0144 & 0.231880 & +1.4\% & 0.9506 & False \\
Format Hudi & 0.1596 & 0.121516 & +17.3\% & 0.1891 & False \\
Format Iceberg & 1.4348 & 0.125418 & +319.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{TPC-DS 100GB, Shuffle Bytes Written}
\end{table}

In [23]:
for format in ['delta', 'hudi', 'iceberg']:

    for target_metric in target_metrics:
        
        for data_set in data_sets:

            df_rq2 = master_df[
                (master_df['format'] == format) &
                (master_df['data_set'] == data_set) 
            ].copy()

            df_rq2['format'] = pd.Categorical(df_rq2['format'], categories=formats)

            y = df_rq2[target_metric].values + EPSILON
            group_data = df_rq2['query'].to_numpy()

            X_df = patsy.dmatrix("C(optimization, Treatment(reference='none')) * C(block_size, Treatment(reference='128MiB'))", data=df_rq2, return_type='dataframe')
            X = X_df.values
            feature_names = X_df.columns.tolist()

            gp_model = gpb.GPModel(group_data=group_data, likelihood='gamma')
            gp_model.fit(y=y, X=X)
            fixed_effects, std_errs = gp_model.get_coef(format_pandas=False, std_err=True)

            summary_data = []
            for name, coef, std_err in zip(feature_names, fixed_effects, std_errs):
                z_stat = coef / std_err
                p_value = 2 * scipy_stats.norm.sf(np.abs(z_stat))
                pct_change = (np.exp(coef) - 1) * 100 if name != 'Intercept' else 0
                
                summary_data.append({
                    'Factor':  'No opt: 128Mib' if name == 'Intercept' else clean_patsy_name(name),
                    'Coefficient $\\beta$': f'{coef:.4f}',
                    'Std. Error': f'{std_err:.4f}' if name != 'Intercept' else '',
                    'Percentage Change': f'{pct_change:+.1f}\\%' if not np.isnan(pct_change) else 'Baseline',
                    '$p$-Value': f'{p_value:.4f}' if name != 'Intercept' else '',
                    '$H_0$ Rejected': str(p_value <= 0.05) if name != 'Intercept' else ''
                })

            summary_df = pd.DataFrame(summary_data)
            caption_text = f'Format {format.capitalize()}, TPC-DS {data_set.split('_')[1]}GB, {re.sub(r'(?<!^)(?=[A-Z])', ' ', target_metric).title()}'
            print_df_latex(summary_df, caption_text)

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 6.1419 &  & +0.0\% &  &  \\
Bloom & -0.0173 & 0.0069 & -1.7\% & 0.0123 & True \\
Partitioning & 0.1538 & 0.0069 & +16.6\% & 0.0000 & True \\
Zorder & 0.0144 & 0.0055 & +1.5\% & 0.0085 & True \\
256Mib & 0.0065 & 0.0055 & +0.7\% & 0.2344 & False \\
64Mib & -0.0306 & 0.0055 & -3.0\% & 0.0000 & True \\
Bloom: 256Mib & -0.0116 & 0.0101 & -1.1\% & 0.2518 & False \\
Partitioning: 256Mib & -0.0165 & 0.0100 & -1.6\% & 0.0972 & False \\
Zorder: 256Mib & -0.0145 & 0.0091 & -1.4\% & 0.1127 & False \\
Bloom: 64Mib & 0.0304 & 0.0101 & +3.1\% & 0.0025 & True \\
Partitioning: 64Mib & 0.0119 & 0.0100 & +1.2\% & 0.2349 & False \\
Zorder: 64Mib & 0.0184 & 0.0092 & +1.9\% & 0.0439 & True \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 7.4085 &  & +0.0\% &  &  \\
Bloom & -0.0170 & 0.0036 & -1.7\% & 0.0000 & True \\
Partitioning & 0.0834 & 0.0044 & +8.7\% & 0.0000 & True \\
Zorder & -0.0180 & 0.0038 & -1.8\% & 0.0000 & True \\
256Mib & 0.0037 & 0.0021 & +0.4\% & 0.0852 & False \\
64Mib & -0.0171 & 0.0044 & -1.7\% & 0.0001 & True \\
Bloom: 256Mib & 0.0065 & 0.0051 & +0.7\% & 0.1977 & False \\
Partitioning: 256Mib & -0.0038 & 0.0060 & -0.4\% & 0.5228 & False \\
Zorder: 256Mib & -0.0009 & 0.0054 & -0.1\% & 0.8613 & False \\
Bloom: 64Mib & 0.0368 & 0.0065 & +3.7\% & 0.0000 & True \\
Partitioning: 64Mib & 0.0306 & 0.0068 & +3.1\% & 0.0000 & True \\
Zorder: 64Mib & 0.0048 & 0.0066 & +0.5\% & 0.4682 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 9.0724 &  & +0.0\% &  &  \\
Bloom & 0.0067 & 0.0070 & +0.7\% & 0.3322 & False \\
Partitioning & -0.0677 & 0.0066 & -6.5\% & 0.0000 & True \\
Zorder & 0.0079 & 0.0067 & +0.8\% & 0.2377 & False \\
256Mib & -0.0157 & 0.0058 & -1.6\% & 0.0068 & True \\
64Mib & 0.0056 & 0.0069 & +0.6\% & 0.4142 & False \\
Bloom: 256Mib & 0.0126 & 0.0092 & +1.3\% & 0.1682 & False \\
Partitioning: 256Mib & -0.0009 & 0.0069 & -0.1\% & 0.8905 & False \\
Zorder: 256Mib & 0.0216 & 0.0099 & +2.2\% & 0.0282 & True \\
Bloom: 64Mib & -0.0099 & 0.0099 & -1.0\% & 0.3177 & False \\
Partitioning: 64Mib & -0.0208 & 0.0096 & -2.1\% & 0.0301 & True \\
Zorder: 64Mib & -0.0174 & 0.0097 & -1.7\% & 0.0714 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 7.3222 &  & +0.0\% &  &  \\
Bloom & 0.0223 & 0.0101 & +2.3\% & 0.0271 & True \\
Partitioning & 1.0572 & 0.0090 & +187.8\% & 0.0000 & True \\
Zorder & 0.0321 & 0.0101 & +3.3\% & 0.0016 & True \\
256Mib & 0.0333 & 0.0072 & +3.4\% & 0.0000 & True \\
64Mib & -0.0478 & 0.0104 & -4.7\% & 0.0000 & True \\
Bloom: 256Mib & -0.0438 & 0.0121 & -4.3\% & 0.0003 & True \\
Partitioning: 256Mib & -0.0485 & 0.0078 & -4.7\% & 0.0000 & True \\
Zorder: 256Mib & -0.0451 & 0.0122 & -4.4\% & 0.0002 & True \\
Bloom: 64Mib & 0.0542 & 0.0152 & +5.6\% & 0.0004 & True \\
Partitioning: 64Mib & 0.0183 & 0.0141 & +1.8\% & 0.1934 & False \\
Zorder: 64Mib & 0.0296 & 0.0152 & +3.0\% & 0.0515 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 9.5393 &  & +0.0\% &  &  \\
Bloom & 0.0024 & 0.0064 & +0.2\% & 0.7031 & False \\
Partitioning & 0.3748 & 0.0062 & +45.5\% & 0.0000 & True \\
Zorder & -0.0760 & 0.0062 & -7.3\% & 0.0000 & True \\
256Mib & 0.0052 & 0.0062 & +0.5\% & 0.3983 & False \\
64Mib & 0.0022 & 0.0073 & +0.2\% & 0.7627 & False \\
Bloom: 256Mib & -0.0161 & 0.0085 & -1.6\% & 0.0590 & False \\
Partitioning: 256Mib & -0.0044 & 0.0075 & -0.4\% & 0.5547 & False \\
Zorder: 256Mib & 0.0033 & 0.0076 & +0.3\% & 0.6643 & False \\
Bloom: 64Mib & 0.0043 & 0.0097 & +0.4\% & 0.6612 & False \\
Partitioning: 64Mib & 0.0196 & 0.0096 & +2.0\% & 0.0412 & True \\
Zorder: 64Mib & -0.0124 & 0.0096 & -1.2\% & 0.1957 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 11.4303 &  & +0.0\% &  &  \\
Bloom & 0.0022 & 0.0053 & +0.2\% & 0.6717 & False \\
Partitioning & -0.0397 & 0.0051 & -3.9\% & 0.0000 & True \\
Zorder & -0.0172 & 0.0047 & -1.7\% & 0.0002 & True \\
256Mib & 0.0025 & 0.0037 & +0.3\% & 0.4982 & False \\
64Mib & 0.0067 & 0.0059 & +0.7\% & 0.2582 & False \\
Bloom: 256Mib & -0.0011 & 0.0076 & -0.1\% & 0.8875 & False \\
Partitioning: 256Mib & -0.0209 & 0.0070 & -2.1\% & 0.0026 & True \\
Zorder: 256Mib & 0.0111 & 0.0071 & +1.1\% & 0.1166 & False \\
Bloom: 64Mib & 0.0085 & 0.0085 & +0.9\% & 0.3200 & False \\
Partitioning: 64Mib & -0.0190 & 0.0085 & -1.9\% & 0.0253 & True \\
Zorder: 64Mib & 0.0015 & 0.0084 & +0.2\% & 0.8589 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 7.6051 &  & +0.0\% &  &  \\
Bloom & 0.0263 & 0.0106 & +2.7\% & 0.0135 & True \\
Partitioning & 0.9368 & 0.0117 & +155.2\% & 0.0000 & True \\
Zorder & 0.0348 & 0.0115 & +3.5\% & 0.0024 & True \\
256Mib & 0.0316 & 0.0092 & +3.2\% & 0.0006 & True \\
64Mib & -0.0171 & 0.0094 & -1.7\% & 0.0674 & False \\
Bloom: 256Mib & -0.0316 & 0.0157 & -3.1\% & 0.0437 & True \\
Partitioning: 256Mib & -0.0459 & 0.0164 & -4.5\% & 0.0051 & True \\
Zorder: 256Mib & -0.0413 & 0.0164 & -4.0\% & 0.0117 & True \\
Bloom: 64Mib & 0.0290 & 0.0158 & +2.9\% & 0.0674 & False \\
Partitioning: 64Mib & -0.0128 & 0.0164 & -1.3\% & 0.4363 & False \\
Zorder: 64Mib & -0.0044 & 0.0164 & -0.4\% & 0.7871 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 9.6446 &  & +0.0\% &  &  \\
Bloom & -0.0001 & 0.0020 & -0.0\% & 0.9434 & False \\
Partitioning & 0.3608 & 0.0065 & +43.5\% & 0.0000 & True \\
Zorder & -0.0679 & 0.0064 & -6.6\% & 0.0000 & True \\
256Mib & 0.0061 & 0.0060 & +0.6\% & 0.3050 & False \\
64Mib & -0.0011 & 0.0066 & -0.1\% & 0.8711 & False \\
Bloom: 256Mib & -0.0099 & 0.0072 & -1.0\% & 0.1722 & False \\
Partitioning: 256Mib & -0.0012 & 0.0095 & -0.1\% & 0.9016 & False \\
Zorder: 256Mib & -0.0032 & 0.0094 & -0.3\% & 0.7373 & False \\
Bloom: 64Mib & 0.0088 & 0.0083 & +0.9\% & 0.2884 & False \\
Partitioning: 64Mib & 0.0259 & 0.0098 & +2.6\% & 0.0080 & True \\
Zorder: 64Mib & -0.0159 & 0.0098 & -1.6\% & 0.1050 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 11.6712 &  & +0.0\% &  &  \\
Bloom & 0.0065 & 0.0074 & +0.7\% & 0.3744 & False \\
Partitioning & -0.0680 & 0.0074 & -6.6\% & 0.0000 & True \\
Zorder & -0.0140 & 0.0044 & -1.4\% & 0.0013 & True \\
256Mib & -0.0135 & 0.0072 & -1.3\% & 0.0596 & False \\
64Mib & 0.0059 & 0.0073 & +0.6\% & 0.4217 & False \\
Bloom: 256Mib & 0.0085 & 0.0102 & +0.9\% & 0.4059 & False \\
Partitioning: 256Mib & 0.0021 & 0.0103 & +0.2\% & 0.8417 & False \\
Zorder: 256Mib & 0.0221 & 0.0075 & +2.2\% & 0.0032 & True \\
Bloom: 64Mib & -0.0098 & 0.0104 & -1.0\% & 0.3466 & False \\
Partitioning: 64Mib & -0.0203 & 0.0104 & -2.0\% & 0.0510 & False \\
Zorder: 64Mib & -0.0122 & 0.0081 & -1.2\% & 0.1290 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Executor Run Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 13.5027 &  & +0.0\% &  &  \\
Bloom & 0.0062 & 0.0086 & +0.6\% & 0.4688 & False \\
Partitioning & 0.1860 & 0.0116 & +20.4\% & 0.0000 & True \\
Zorder & 0.0042 & 0.0102 & +0.4\% & 0.6835 & False \\
256Mib & 0.0054 & 0.0092 & +0.5\% & 0.5567 & False \\
64Mib & 0.0095 & 0.0091 & +1.0\% & 0.2932 & False \\
Bloom: 256Mib & -0.0038 & 0.0153 & -0.4\% & 0.8051 & False \\
Partitioning: 256Mib & -0.0324 & 0.0168 & -3.2\% & 0.0539 & False \\
Zorder: 256Mib & 0.0028 & 0.0161 & +0.3\% & 0.8643 & False \\
Bloom: 64Mib & -0.0148 & 0.0152 & -1.5\% & 0.3303 & False \\
Partitioning: 64Mib & -0.0053 & 0.0167 & -0.5\% & 0.7499 & False \\
Zorder: 64Mib & -0.0071 & 0.0161 & -0.7\% & 0.6614 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 14.7323 &  & +0.0\% &  &  \\
Bloom & 0.0003 & 0.0011 & +0.0\% & 0.7954 & False \\
Partitioning & 0.0264 & 0.0011 & +2.7\% & 0.0000 & True \\
Zorder & 0.0001 & 0.0001 & +0.0\% & 0.4120 & False \\
256Mib & -0.0001 & 0.0011 & -0.0\% & 0.9250 & False \\
64Mib & -0.0004 & 0.0011 & -0.0\% & 0.7418 & False \\
Bloom: 256Mib & 0.0012 & 0.0016 & +0.1\% & 0.4844 & False \\
Partitioning: 256Mib & 0.0003 & 0.0017 & +0.0\% & 0.8398 & False \\
Zorder: 256Mib & 0.0001 & 0.0012 & +0.0\% & 0.9050 & False \\
Bloom: 64Mib & -0.0003 & 0.0016 & -0.0\% & 0.8731 & False \\
Partitioning: 64Mib & 0.0006 & 0.0017 & +0.1\% & 0.7174 & False \\
Zorder: 64Mib & 0.0015 & 0.0012 & +0.1\% & 0.2268 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 15.0081 &  & +0.0\% &  &  \\
Bloom & -0.0046 & 0.0039 & -0.5\% & 0.2470 & False \\
Partitioning & 0.1063 & 0.0043 & +11.2\% & 0.0000 & True \\
Zorder & 0.0148 & 0.0039 & +1.5\% & 0.0001 & True \\
256Mib & -0.0048 & 0.0046 & -0.5\% & 0.3029 & False \\
64Mib & -0.0047 & 0.0039 & -0.5\% & 0.2256 & False \\
Bloom: 256Mib & 0.0058 & 0.0066 & +0.6\% & 0.3745 & False \\
Partitioning: 256Mib & 0.0062 & 0.0065 & +0.6\% & 0.3424 & False \\
Zorder: 256Mib & 0.0058 & 0.0066 & +0.6\% & 0.3780 & False \\
Bloom: 64Mib & 0.0058 & 0.0061 & +0.6\% & 0.3404 & False \\
Partitioning: 64Mib & 0.0062 & 0.0063 & +0.6\% & 0.3275 & False \\
Zorder: 64Mib & 0.0060 & 0.0060 & +0.6\% & 0.3187 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Result Size}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 19.9091 &  & +0.0\% &  &  \\
Bloom & 0.0068 & 0.0326 & +0.7\% & 0.8346 & False \\
Partitioning & 0.4561 & 0.0519 & +57.8\% & 0.0000 & True \\
Zorder & 0.0097 & 0.0431 & +1.0\% & 0.8225 & False \\
256Mib & -0.0052 & 0.0348 & -0.5\% & 0.8813 & False \\
64Mib & -0.0057 & 0.0415 & -0.6\% & 0.8911 & False \\
Bloom: 256Mib & 0.0016 & 0.0525 & +0.2\% & 0.9753 & False \\
Partitioning: 256Mib & 0.0106 & 0.0730 & +1.1\% & 0.8841 & False \\
Zorder: 256Mib & 0.0010 & 0.0677 & +0.1\% & 0.9878 & False \\
Bloom: 64Mib & 0.0010 & 0.0654 & +0.1\% & 0.9883 & False \\
Partitioning: 64Mib & 0.0090 & 0.0755 & +0.9\% & 0.9055 & False \\
Zorder: 64Mib & -0.0016 & 0.0712 & -0.2\% & 0.9818 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 21.4443 &  & +0.0\% &  &  \\
Bloom & 0.0230 & 0.0238 & +2.3\% & 0.3334 & False \\
Partitioning & 0.1216 & 0.0273 & +12.9\% & 0.0000 & True \\
Zorder & -0.0148 & 0.0271 & -1.5\% & 0.5858 & False \\
256Mib & 0.0293 & 0.0220 & +3.0\% & 0.1839 & False \\
64Mib & 0.0284 & 0.0265 & +2.9\% & 0.2827 & False \\
Bloom: 256Mib & -0.0343 & 0.0246 & -3.4\% & 0.1626 & False \\
Partitioning: 256Mib & -0.0312 & 0.0325 & -3.1\% & 0.3367 & False \\
Zorder: 256Mib & -0.0368 & 0.0320 & -3.6\% & 0.2498 & False \\
Bloom: 64Mib & -0.0316 & 0.0324 & -3.1\% & 0.3296 & False \\
Partitioning: 64Mib & -0.0310 & 0.0369 & -3.1\% & 0.4001 & False \\
Zorder: 64Mib & -0.0417 & 0.0366 & -4.1\% & 0.2547 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 22.8450 &  & +0.0\% &  &  \\
Bloom & -0.0395 & 0.0222 & -3.9\% & 0.0745 & False \\
Partitioning & -0.0225 & 0.0224 & -2.2\% & 0.3151 & False \\
Zorder & -0.1176 & 0.0255 & -11.1\% & 0.0000 & True \\
256Mib & -0.0377 & 0.0186 & -3.7\% & 0.0427 & True \\
64Mib & -0.0360 & 0.0279 & -3.5\% & 0.1965 & False \\
Bloom: 256Mib & 0.0508 & 0.0346 & +5.2\% & 0.1414 & False \\
Partitioning: 256Mib & 0.0479 & 0.0344 & +4.9\% & 0.1635 & False \\
Zorder: 256Mib & 0.0396 & 0.0371 & +4.0\% & 0.2866 & False \\
Bloom: 64Mib & 0.0504 & 0.0403 & +5.2\% & 0.2104 & False \\
Partitioning: 64Mib & 0.0479 & 0.0403 & +4.9\% & 0.2348 & False \\
Zorder: 64Mib & 0.0391 & 0.0409 & +4.0\% & 0.3393 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Peak Execution Memory}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 14.8863 &  & +0.0\% &  &  \\
Bloom & -0.0029 & 0.0406 & -0.3\% & 0.9433 & False \\
Partitioning & 0.7782 & 0.0555 & +117.8\% & 0.0000 & True \\
Zorder & -0.0024 & 0.0411 & -0.2\% & 0.9541 & False \\
256Mib & -0.0013 & 0.0363 & -0.1\% & 0.9721 & False \\
64Mib & -0.0012 & 0.0518 & -0.1\% & 0.9810 & False \\
Bloom: 256Mib & 0.0005 & 0.0552 & +0.0\% & 0.9932 & False \\
Partitioning: 256Mib & 0.0099 & 0.0704 & +1.0\% & 0.8888 & False \\
Zorder: 256Mib & 0.0056 & 0.0578 & +0.6\% & 0.9230 & False \\
Bloom: 64Mib & 0.0023 & 0.0729 & +0.2\% & 0.9745 & False \\
Partitioning: 64Mib & 0.0068 & 0.0740 & +0.7\% & 0.9262 & False \\
Zorder: 64Mib & 0.0028 & 0.0730 & +0.3\% & 0.9697 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 18.2070 &  & +0.0\% &  &  \\
Bloom & -0.0044 & 0.0068 & -0.4\% & 0.5213 & False \\
Partitioning & 0.1371 & 0.0086 & +14.7\% & 0.0000 & True \\
Zorder & -0.0179 & 0.0086 & -1.8\% & 0.0374 & True \\
256Mib & 0.0014 & 0.0055 & +0.1\% & 0.8014 & False \\
64Mib & 0.0016 & 0.0071 & +0.2\% & 0.8198 & False \\
Bloom: 256Mib & 0.0016 & 0.0088 & +0.2\% & 0.8523 & False \\
Partitioning: 256Mib & -0.0014 & 0.0117 & -0.1\% & 0.9045 & False \\
Zorder: 256Mib & 0.0009 & 0.0120 & +0.1\% & 0.9420 & False \\
Bloom: 64Mib & 0.0032 & 0.0114 & +0.3\% & 0.7809 & False \\
Partitioning: 64Mib & -0.0023 & 0.0124 & -0.2\% & 0.8535 & False \\
Zorder: 64Mib & 0.0007 & 0.0125 & +0.1\% & 0.9562 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 19.9919 &  & +0.0\% &  &  \\
Bloom & 0.0090 & 0.0168 & +0.9\% & 0.5923 & False \\
Partitioning & -0.2013 & 0.0181 & -18.2\% & 0.0000 & True \\
Zorder & -0.2052 & 0.0179 & -18.6\% & 0.0000 & True \\
256Mib & 0.0042 & 0.0181 & +0.4\% & 0.8178 & False \\
64Mib & 0.0062 & 0.0179 & +0.6\% & 0.7285 & False \\
Bloom: 256Mib & -0.0098 & 0.0238 & -1.0\% & 0.6820 & False \\
Partitioning: 256Mib & -0.0062 & 0.0246 & -0.6\% & 0.8000 & False \\
Zorder: 256Mib & -0.0035 & 0.0246 & -0.4\% & 0.8854 & False \\
Bloom: 64Mib & -0.0085 & 0.0247 & -0.8\% & 0.7310 & False \\
Partitioning: 64Mib & -0.0044 & 0.0252 & -0.4\% & 0.8605 & False \\
Zorder: 64Mib & -0.0026 & 0.0253 & -0.3\% & 0.9179 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 100GB, Shuffle Total Bytes Read}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 14.5819 &  & +0.0\% &  &  \\
Bloom & -0.0047 & 0.0507 & -0.5\% & 0.9268 & False \\
Partitioning & 0.8032 & 0.0632 & +123.3\% & 0.0000 & True \\
Zorder & -0.0037 & 0.0524 & -0.4\% & 0.9430 & False \\
256Mib & -0.0044 & 0.0542 & -0.4\% & 0.9357 & False \\
64Mib & -0.0038 & 0.0447 & -0.4\% & 0.9314 & False \\
Bloom: 256Mib & 0.0039 & 0.0810 & +0.4\% & 0.9620 & False \\
Partitioning: 256Mib & 0.0065 & 0.0824 & +0.6\% & 0.9374 & False \\
Zorder: 256Mib & 0.0084 & 0.0814 & +0.8\% & 0.9175 & False \\
Bloom: 64Mib & 0.0060 & 0.0769 & +0.6\% & 0.9381 & False \\
Partitioning: 64Mib & 0.0089 & 0.0816 & +0.9\% & 0.9129 & False \\
Zorder: 64Mib & 0.0039 & 0.0780 & +0.4\% & 0.9604 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 1GB, Shuffle Bytes Written}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 18.0122 &  & +0.0\% &  &  \\
Bloom & -0.0068 & 0.0088 & -0.7\% & 0.4427 & False \\
Partitioning & 0.1217 & 0.0092 & +12.9\% & 0.0000 & True \\
Zorder & -0.0223 & 0.0079 & -2.2\% & 0.0051 & True \\
256Mib & -0.0090 & 0.0087 & -0.9\% & 0.2999 & False \\
64Mib & -0.0091 & 0.0087 & -0.9\% & 0.2968 & False \\
Bloom: 256Mib & 0.0104 & 0.0125 & +1.0\% & 0.4070 & False \\
Partitioning: 256Mib & 0.0118 & 0.0126 & +1.2\% & 0.3498 & False \\
Zorder: 256Mib & 0.0098 & 0.0119 & +1.0\% & 0.4119 & False \\
Bloom: 64Mib & 0.0098 & 0.0125 & +1.0\% & 0.4319 & False \\
Partitioning: 64Mib & 0.0117 & 0.0126 & +1.2\% & 0.3537 & False \\
Zorder: 64Mib & 0.0097 & 0.0119 & +1.0\% & 0.4147 & False \\
\bottomrule
\end{tabular}
\caption{Format Delta, TPC-DS 10GB, Shuffle Bytes Written}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coefficient $\beta$ & Std. Error & Percentage Change & $p$-Value & $H_0$ Rejected \\
\midrule
No opt: 128Mib & 19.7125 &  & +0.0\% &  &  \\
Bloom & 0.0063 & 0.0141 & +0.6\% & 0.6545 & False \\
Partitioning & -0.1979 & 0.0182 & -18.0\% & 0.0000 & True \\
Zorder & -0.1993 & 0.0179 & -18.1\% & 0.0000 & True \\
256Mib & 0.0060 & 0.0156 & +0.6\% & 0.7014 & False \\
64Mib & 0.0061 & 0.0141 & +0.6\% & 0.6663 & False \\
Bloom: 256Mib & -0.0076 & 0.0238 & -0.8\% & 0.7512 & False \\
Partitioning: 256Mib & -0.0088 & 0.0254 & -0.9\% & 0.7303 & False \\
Zorder: 256Mib & -0.0076 & 0.0254 & -0.8\% & 0.7658 & False \\
Bloom: 64Mib & -0.0077 & 0.0229 & -0.8\% & 0.7350 & False \\

In [24]:
for target_metric in target_metrics:
        
    for data_set in data_sets:

        for optimization in optimizations:

            df_rq3 = master_df[
                ((master_df['format'] == 'parquet') & (master_df['data_set'] == data_set)) |
                ((master_df['format'] != 'parquet') & (master_df['data_set'] == data_set) & (master_df['optimization'] == optimization))
            ].copy()

            # df_rq3['format'] = pd.Categorical(df_rq3['format'], categories=formats)
            df_rq3['format_variation'] = df_rq3['format'] + '_' + df_rq3['optimization'] + '_' + df_rq3['block_size'].astype(str)

            y = df_rq3[target_metric].values + EPSILON
            group_data = df_rq3['query'].to_numpy()

            X_df = patsy.dmatrix("C(format_variation, Treatment(reference='parquet_none_128MiB'))", data=df_rq3, return_type='dataframe')
            X = X_df.values
            feature_names = X_df.columns.tolist()

            gp_model = gpb.GPModel(group_data=group_data, likelihood='gamma')
            gp_model.fit(y=y, X=X)
            fixed_effects, std_errs = gp_model.get_coef(format_pandas=False, std_err=True)

            summary_data = []
            for name, coef, std_err in zip(feature_names, fixed_effects, std_errs):
                z_stat = coef / std_err
                p_value = 2 * scipy_stats.norm.sf(np.abs(z_stat))
                pct_change = (np.exp(coef) - 1) * 100 if name != 'Intercept' else 0
                
                summary_data.append({
                    'Factor': 'Parquet None 128MiB' if name == 'Intercept' else clean_patsy_name(name).replace('_', ' '),
                    'Coef. $\\beta$': f'{coef:.4f}',
                    'Std. Error': f'{std_err:.4f}' if name != 'Intercept' else '',
                    'Pct. Change': f'{pct_change:+.1f}\\%',
                    '$p$-Value': f'{p_value:.4f}' if name != 'Intercept' else '',
                    '$H_0$ Rejected': str(p_value <= 0.05) if name != 'Intercept' else ''
                })

            summary_df = pd.DataFrame(summary_data)
            caption_text=f'Optimization {optimization.capitalize()}, TPC-DS {data_set.split('_')[1]}GB, {re.sub(r'(?<!^)(?=[A-Z])', ' ', target_metric).title()}'
            print_df_latex(summary_df, caption_text)

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.1632 &  & +0.0\% &  &  \\
Delta None 128Mib & 1.2596 & 0.0177 & +252.4\% & 0.0000 & True \\
Delta None 256Mib & 1.2796 & 0.0177 & +259.5\% & 0.0000 & True \\
Delta None 64Mib & 1.2255 & 0.0177 & +240.6\% & 0.0000 & True \\
Hudi None 128Mib & 0.1565 & 0.0169 & +16.9\% & 0.0000 & True \\
Hudi None 256Mib & 0.1563 & 0.0169 & +16.9\% & 0.0000 & True \\
Hudi None 64Mib & 0.0678 & 0.0169 & +7.0\% & 0.0001 & True \\
Iceberg None 128Mib & 0.0235 & 0.0169 & +2.4\% & 0.1624 & False \\
Iceberg None 256Mib & 0.0238 & 0.0121 & +2.4\% & 0.0492 & True \\
Iceberg None 64Mib & -0.0248 & 0.0077 & -2.5\% & 0.0012 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.1572 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & 1.2840 & 0.0170 & +261.1\% & 0.0000 & True \\
Delta Zorder 256Mib & 1.2771 & 0.0170 & +258.6\% & 0.0000 & True \\
Delta Zorder 64Mib & 1.2682 & 0.0170 & +255.4\% & 0.0000 & True \\
Hudi Zorder 128Mib & 0.1557 & 0.0161 & +16.9\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.1565 & 0.0161 & +16.9\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.0637 & 0.0123 & +6.6\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.0173 & 0.0122 & +1.7\% & 0.1586 & False \\
Iceberg Zorder 256Mib & 0.0225 & 0.0143 & +2.3\% & 0.1151 & False \\
Iceberg Zorder 64Mib & -0.0104 & 0.0120 & -1.0\% & 0.3877 & False \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.1618 &  & +0.0\% &  &  \\
Delta Bloom 128Mib & 1.2482 & 0.0178 & +248.4\% & 0.0000 & True \\
Delta Bloom 256Mib & 1.2402 & 0.0177 & +245.6\% & 0.0000 & True \\
Delta Bloom 64Mib & 1.2448 & 0.0177 & +247.2\% & 0.0000 & True \\
Hudi Bloom 128Mib & 0.1507 & 0.0169 & +16.3\% & 0.0000 & True \\
Hudi Bloom 256Mib & 0.1567 & 0.0170 & +17.0\% & 0.0000 & True \\
Hudi Bloom 64Mib & 0.0653 & 0.0170 & +6.7\% & 0.0001 & True \\
Iceberg Bloom 128Mib & 0.0121 & 0.0169 & +1.2\% & 0.4761 & False \\
Iceberg Bloom 256Mib & 0.0223 & 0.0142 & +2.3\% & 0.1167 & False \\
Iceberg Bloom 64Mib & -0.0316 & 0.0049 & -3.1\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Bloom, TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.3639 &  & +0.0\% &  &  \\
Delta Partitioning 128Mib & 1.1103 & 0.0220 & +203.5\% & 0.0000 & True \\
Delta Partitioning 256Mib & 1.0985 & 0.0220 & +200.0\% & 0.0000 & True \\
Delta Partitioning 64Mib & 1.0887 & 0.0219 & +197.0\% & 0.0000 & True \\
Hudi Partitioning 128Mib & 0.3761 & 0.0216 & +45.7\% & 0.0000 & True \\
Hudi Partitioning 256Mib & 0.3702 & 0.0216 & +44.8\% & 0.0000 & True \\
Hudi Partitioning 64Mib & 0.3778 & 0.0216 & +45.9\% & 0.0000 & True \\
Iceberg Partitioning 128Mib & 0.2801 & 0.0218 & +32.3\% & 0.0000 & True \\
Iceberg Partitioning 256Mib & 0.3006 & 0.0218 & +35.1\% & 0.0000 & True \\
Iceberg Partitioning 64Mib & 0.3226 & 0.0217 & +38.1\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Partitioning, TPC-DS 1GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 7.2412 &  & +0.0\% &  &  \\
Delta None 128Mib & 0.2484 & 0.0058 & +28.2\% & 0.0000 & True \\
Delta None 256Mib & 0.2516 & 0.0057 & +28.6\% & 0.0000 & True \\
Delta None 64Mib & 0.2309 & 0.0057 & +26.0\% & 0.0000 & True \\
Hudi None 128Mib & 0.0769 & 0.0057 & +8.0\% & 0.0000 & True \\
Hudi None 256Mib & 0.0727 & 0.0057 & +7.5\% & 0.0000 & True \\
Hudi None 64Mib & 0.1775 & 0.0057 & +19.4\% & 0.0000 & True \\
Iceberg None 128Mib & 0.0670 & 0.0057 & +6.9\% & 0.0000 & True \\
Iceberg None 256Mib & 0.0658 & 0.0011 & +6.8\% & 0.0000 & True \\
Iceberg None 64Mib & 0.1115 & 0.0052 & +11.8\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 7.2653 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & 0.2302 & 0.0067 & +25.9\% & 0.0000 & True \\
Delta Zorder 256Mib & 0.2316 & 0.0067 & +26.1\% & 0.0000 & True \\
Delta Zorder 64Mib & 0.2177 & 0.0067 & +24.3\% & 0.0000 & True \\
Hudi Zorder 128Mib & 0.0734 & 0.0054 & +7.6\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.0886 & 0.0067 & +9.3\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.1850 & 0.0067 & +20.3\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.1235 & 0.0044 & +13.1\% & 0.0000 & True \\
Iceberg Zorder 256Mib & 0.1950 & 0.0048 & +21.5\% & 0.0000 & True \\
Iceberg Zorder 64Mib & 0.1731 & 0.0067 & +18.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 7.2421 &  & +0.0\% &  &  \\
Delta Bloom 128Mib & 0.2308 & 0.0054 & +26.0\% & 0.0000 & True \\
Delta Bloom 256Mib & 0.2412 & 0.0054 & +27.3\% & 0.0000 & True \\
Delta Bloom 64Mib & 0.2511 & 0.0054 & +28.5\% & 0.0000 & True \\
Hudi Bloom 128Mib & 0.0750 & 0.0040 & +7.8\% & 0.0000 & True \\
Hudi Bloom 256Mib & 0.0744 & 0.0051 & +7.7\% & 0.0000 & True \\
Hudi Bloom 64Mib & 0.1794 & 0.0054 & +19.6\% & 0.0000 & True \\
Iceberg Bloom 128Mib & 0.0575 & 0.0046 & +5.9\% & 0.0000 & True \\
Iceberg Bloom 256Mib & 0.0275 & 0.0054 & +2.8\% & 0.0000 & True \\
Iceberg Bloom 64Mib & 0.1184 & 0.0034 & +12.6\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Bloom, TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 7.1502 &  & +0.0\% &  &  \\
Delta Partitioning 128Mib & 0.3114 & 0.0070 & +36.5\% & 0.0000 & True \\
Delta Partitioning 256Mib & 0.3113 & 0.0070 & +36.5\% & 0.0000 & True \\
Delta Partitioning 64Mib & 0.3258 & 0.0070 & +38.5\% & 0.0000 & True \\
Hudi Partitioning 128Mib & 0.1893 & 0.0070 & +20.8\% & 0.0000 & True \\
Hudi Partitioning 256Mib & 0.2161 & 0.0070 & +24.1\% & 0.0000 & True \\
Hudi Partitioning 64Mib & 0.2364 & 0.0070 & +26.7\% & 0.0000 & True \\
Iceberg Partitioning 128Mib & 0.1935 & 0.0070 & +21.4\% & 0.0000 & True \\
Iceberg Partitioning 256Mib & 0.1722 & 0.0070 & +18.8\% & 0.0000 & True \\
Iceberg Partitioning 64Mib & 0.1700 & 0.0070 & +18.5\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Partitioning, TPC-DS 10GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 8.9992 &  & +0.0\% &  &  \\
Delta None 128Mib & 0.0859 & 0.0137 & +9.0\% & 0.0000 & True \\
Delta None 256Mib & 0.0679 & 0.0136 & +7.0\% & 0.0000 & True \\
Delta None 64Mib & 0.0868 & nan & +9.1\% & nan & False \\
Hudi None 128Mib & 0.1614 & 0.0136 & +17.5\% & 0.0000 & True \\
Hudi None 256Mib & 0.1425 & 0.0136 & +15.3\% & 0.0000 & True \\
Hudi None 64Mib & 0.1426 & 0.0136 & +15.3\% & 0.0000 & True \\
Iceberg None 128Mib & 0.4641 & 0.0139 & +59.1\% & 0.0000 & True \\
Iceberg None 256Mib & 0.4894 & 0.0139 & +63.1\% & 0.0000 & True \\
Iceberg None 64Mib & 0.5220 & 0.0140 & +68.5\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 8.5393 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & 0.0843 & 0.0152 & +8.8\% & 0.0000 & True \\
Delta Zorder 256Mib & 0.0915 & 0.0152 & +9.6\% & 0.0000 & True \\
Delta Zorder 64Mib & 0.0752 & nan & +7.8\% & nan & False \\
Hudi Zorder 128Mib & 0.1435 & 0.0152 & +15.4\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.1549 & 0.0152 & +16.8\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.1568 & 0.0152 & +17.0\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.5387 & 0.0155 & +71.4\% & 0.0000 & True \\
Iceberg Zorder 256Mib & 0.6025 & 0.0156 & +82.7\% & 0.0000 & True \\
Iceberg Zorder 64Mib & 0.6487 & 0.0155 & +91.3\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 8.9985 &  & +0.0\% &  &  \\
Delta Bloom 128Mib & 0.0870 & 0.0136 & +9.1\% & 0.0000 & True \\
Delta Bloom 256Mib & 0.0852 & nan & +8.9\% & nan & False \\
Delta Bloom 64Mib & 0.0865 & 0.0134 & +9.0\% & 0.0000 & True \\
Hudi Bloom 128Mib & 0.1531 & 0.0134 & +16.5\% & 0.0000 & True \\
Hudi Bloom 256Mib & 0.1358 & 0.0134 & +14.6\% & 0.0000 & True \\
Hudi Bloom 64Mib & 0.1511 & 0.0134 & +16.3\% & 0.0000 & True \\
Iceberg Bloom 128Mib & 0.4920 & 0.0137 & +63.6\% & 0.0000 & True \\
Iceberg Bloom 256Mib & 0.4724 & 0.0137 & +60.4\% & 0.0000 & True \\
Iceberg Bloom 64Mib & 0.5317 & 0.0137 & +70.2\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Bloom, TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 9.0094 &  & +0.0\% &  &  \\
Delta Partitioning 128Mib & 0.0035 & 0.0096 & +0.4\% & 0.7137 & False \\
Delta Partitioning 256Mib & -0.0140 & 0.0096 & -1.4\% & 0.1451 & False \\
Delta Partitioning 64Mib & -0.0129 & 0.0096 & -1.3\% & 0.1792 & False \\
Hudi Partitioning 128Mib & 0.0968 & 0.0096 & +10.2\% & 0.0000 & True \\
Hudi Partitioning 256Mib & 0.0921 & 0.0122 & +9.6\% & 0.0000 & True \\
Hudi Partitioning 64Mib & 0.0851 & 0.0122 & +8.9\% & 0.0000 & True \\
Iceberg Partitioning 128Mib & 0.4737 & 0.0126 & +60.6\% & 0.0000 & True \\
Iceberg Partitioning 256Mib & 0.4416 & 0.0125 & +55.5\% & 0.0000 & True \\
Iceberg Partitioning 64Mib & 0.4341 & 0.0125 & +54.4\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Partitioning, TPC-DS 100GB, Elapsed Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.6302 &  & +0.0\% &  &  \\
Delta None 128Mib & 2.0548 & 0.0315 & +680.5\% & 0.0000 & True \\
Delta None 256Mib & 2.0983 & 0.0315 & +715.2\% & 0.0000 & True \\
Delta None 64Mib & 1.9975 & 0.0314 & +637.1\% & 0.0000 & True \\
Hudi None 128Mib & 0.3171 & 0.0287 & +37.3\% & 0.0000 & True \\
Hudi None 256Mib & 0.3194 & 0.0287 & +37.6\% & 0.0000 & True \\
Hudi None 64Mib & 0.4650 & 0.0287 & +59.2\% & 0.0000 & True \\
Iceberg None 128Mib & 0.0836 & 0.0286 & +8.7\% & 0.0035 & True \\
Iceberg None 256Mib & 0.0846 & nan & +8.8\% & nan & False \\
Iceberg None 64Mib & 0.2143 & 0.0286 & +23.9\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.6312 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & 2.0909 & 0.0354 & +709.2\% & 0.0000 & True \\
Delta Zorder 256Mib & 2.0801 & 0.0354 & +700.5\% & 0.0000 & True \\
Delta Zorder 64Mib & 2.0691 & 0.0354 & +691.8\% & 0.0000 & True \\
Hudi Zorder 128Mib & 0.3153 & 0.0331 & +37.1\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.3187 & 0.0331 & +37.5\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.4721 & 0.0331 & +60.3\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.0782 & 0.0332 & +8.1\% & 0.0186 & True \\
Iceberg Zorder 256Mib & 0.0788 & 0.0332 & +8.2\% & 0.0177 & True \\
Iceberg Zorder 64Mib & 0.2251 & 0.0332 & +25.2\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.6306 &  & +0.0\% &  &  \\
Delta Bloom 128Mib & 2.0834 & 0.0315 & +703.2\% & 0.0000 & True \\
Delta Bloom 256Mib & 2.0684 & 0.0315 & +691.2\% & 0.0000 & True \\
Delta Bloom 64Mib & 2.0898 & 0.0315 & +708.3\% & 0.0000 & True \\
Hudi Bloom 128Mib & 0.3144 & 0.0287 & +36.9\% & 0.0000 & True \\
Hudi Bloom 256Mib & 0.3222 & 0.0287 & +38.0\% & 0.0000 & True \\
Hudi Bloom 64Mib & 0.4673 & 0.0287 & +59.6\% & 0.0000 & True \\
Iceberg Bloom 128Mib & 0.0805 & 0.0286 & +8.4\% & 0.0049 & True \\
Iceberg Bloom 256Mib & 0.0859 & nan & +9.0\% & nan & False \\
Iceberg Bloom 64Mib & 0.2165 & 0.0286 & +24.2\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Bloom, TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 5.7249 &  & +0.0\% &  &  \\
Delta Partitioning 128Mib & 2.7662 & 0.0336 & +1489.8\% & 0.0000 & True \\
Delta Partitioning 256Mib & 2.7668 & 0.0336 & +1490.7\% & 0.0000 & True \\
Delta Partitioning 64Mib & 2.7110 & 0.0335 & +1404.5\% & 0.0000 & True \\
Hudi Partitioning 128Mib & 1.8881 & 0.0327 & +560.7\% & 0.0000 & True \\
Hudi Partitioning 256Mib & 1.8923 & 0.0327 & +563.5\% & 0.0000 & True \\
Hudi Partitioning 64Mib & 1.8999 & 0.0327 & +568.5\% & 0.0000 & True \\
Iceberg Partitioning 128Mib & 1.5570 & 0.0327 & +374.5\% & 0.0000 & True \\
Iceberg Partitioning 256Mib & 1.6236 & 0.0328 & +407.1\% & 0.0000 & True \\
Iceberg Partitioning 64Mib & 1.6433 & 0.0327 & +417.2\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Partitioning, TPC-DS 1GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 9.4220 &  & +0.0\% &  &  \\
Delta None 128Mib & 0.1387 & 0.0073 & +14.9\% & 0.0000 & True \\
Delta None 256Mib & 0.1454 & 0.0073 & +15.6\% & 0.0000 & True \\
Delta None 64Mib & 0.1420 & 0.0073 & +15.3\% & 0.0000 & True \\
Hudi None 128Mib & 0.1132 & 0.0073 & +12.0\% & 0.0000 & True \\
Hudi None 256Mib & 0.1038 & 0.0045 & +10.9\% & 0.0000 & True \\
Hudi None 64Mib & 0.4129 & 0.0073 & +51.1\% & 0.0000 & True \\
Iceberg None 128Mib & 0.1104 & 0.0045 & +11.7\% & 0.0000 & True \\
Iceberg None 256Mib & 0.1059 & 0.0070 & +11.2\% & 0.0000 & True \\
Iceberg None 64Mib & 0.3256 & 0.0073 & +38.5\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 9.4466 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & 0.0513 & 0.0083 & +5.3\% & 0.0000 & True \\
Delta Zorder 256Mib & 0.0586 & 0.0076 & +6.0\% & 0.0000 & True \\
Delta Zorder 64Mib & 0.0394 & 0.0067 & +4.0\% & 0.0000 & True \\
Hudi Zorder 128Mib & 0.1095 & 0.0067 & +11.6\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.1253 & 0.0067 & +13.3\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.4172 & 0.0082 & +51.8\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.0847 & 0.0076 & +8.8\% & 0.0000 & True \\
Iceberg Zorder 256Mib & -0.0711 & 0.0067 & -6.9\% & 0.0000 & True \\
Iceberg Zorder 64Mib & 0.3295 & 0.0082 & +39.0\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 9.4229 &  & +0.0\% &  &  \\
Delta Bloom 128Mib & 0.1421 & 0.0089 & +15.3\% & 0.0000 & True \\
Delta Bloom 256Mib & 0.1302 & 0.0089 & +13.9\% & 0.0000 & True \\
Delta Bloom 64Mib & 0.1483 & 0.0089 & +16.0\% & 0.0000 & True \\
Hudi Bloom 128Mib & 0.1169 & 0.0089 & +12.4\% & 0.0000 & True \\
Hudi Bloom 256Mib & 0.1063 & 0.0089 & +11.2\% & 0.0000 & True \\
Hudi Bloom 64Mib & 0.4156 & 0.0089 & +51.5\% & 0.0000 & True \\
Iceberg Bloom 128Mib & 0.1073 & 0.0089 & +11.3\% & 0.0000 & True \\
Iceberg Bloom 256Mib & 0.0699 & 0.0089 & +7.2\% & 0.0000 & True \\
Iceberg Bloom 64Mib & 0.3336 & 0.0089 & +39.6\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Bloom, TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 9.3395 &  & +0.0\% &  &  \\
Delta Partitioning 128Mib & 0.4524 & 0.0088 & +57.2\% & 0.0000 & True \\
Delta Partitioning 256Mib & 0.4528 & 0.0088 & +57.3\% & 0.0000 & True \\
Delta Partitioning 64Mib & 0.4734 & 0.0088 & +60.5\% & 0.0000 & True \\
Hudi Partitioning 128Mib & 0.4655 & 0.0088 & +59.3\% & 0.0000 & True \\
Hudi Partitioning 256Mib & 0.4991 & 0.0088 & +64.7\% & 0.0000 & True \\
Hudi Partitioning 64Mib & 0.5242 & 0.0088 & +68.9\% & 0.0000 & True \\
Iceberg Partitioning 128Mib & 0.4625 & 0.0088 & +58.8\% & 0.0000 & True \\
Iceberg Partitioning 256Mib & 0.4539 & 0.0088 & +57.4\% & 0.0000 & True \\
Iceberg Partitioning 64Mib & 0.4602 & 0.0088 & +58.4\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Partitioning, TPC-DS 10GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 11.3606 &  & +0.0\% &  &  \\
Delta None 128Mib & 0.0237 & 0.0092 & +2.4\% & 0.0103 & True \\
Delta None 256Mib & 0.0238 & 0.0081 & +2.4\% & 0.0033 & True \\
Delta None 64Mib & 0.0265 & 0.0068 & +2.7\% & 0.0001 & True \\
Hudi None 128Mib & 0.2028 & 0.0068 & +22.5\% & 0.0000 & True \\
Hudi None 256Mib & 0.2028 & 0.0068 & +22.5\% & 0.0000 & True \\
Hudi None 64Mib & 0.2040 & 0.0091 & +22.6\% & 0.0000 & True \\
Iceberg None 128Mib & 0.3704 & 0.0092 & +44.8\% & 0.0000 & True \\
Iceberg None 256Mib & 0.3648 & 0.0092 & +44.0\% & 0.0000 & True \\
Iceberg None 64Mib & 0.3629 & 0.0092 & +43.8\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization None, TPC-DS 100GB, Executor Cpu Time}
\end{table}

\begin{table}[h!]
\centering
\begin{tabular}{llllll}
\toprule
Factor & Coef. $\beta$ & Std. Error & Pct. Change & $p$-Value & $H_0$ Rejected \\
\midrule
Parquet None 128MiB & 11.3480 &  & +0.0\% &  &  \\
Delta Zorder 128Mib & -0.0017 & 0.0084 & -0.2\% & 0.8390 & False \\
Delta Zorder 256Mib & 0.0117 & 0.0085 & +1.2\% & 0.1659 & False \\
Delta Zorder 64Mib & 0.0061 & 0.0092 & +0.6\% & 0.5037 & False \\
Hudi Zorder 128Mib & 0.2058 & 0.0085 & +22.8\% & 0.0000 & True \\
Hudi Zorder 256Mib & 0.2055 & 0.0085 & +22.8\% & 0.0000 & True \\
Hudi Zorder 64Mib & 0.2111 & 0.0097 & +23.5\% & 0.0000 & True \\
Iceberg Zorder 128Mib & 0.3817 & 0.0105 & +46.5\% & 0.0000 & True \\
Iceberg Zorder 256Mib & 0.3642 & 0.0105 & +43.9\% & 0.0000 & True \\
Iceberg Zorder 64Mib & 0.4152 & 0.0105 & +51.5\% & 0.0000 & True \\
\bottomrule
\end{tabular}
\caption{Optimization Zorder, TPC-DS 100GB, Executor Cpu Time}
\end{table}
